export const SETTINGS = {
    dots: true,
    arrows: true,
    infinite: false,
    edgeFriction: false,
    pauseOnHover: false,
    slidesToShow: true,
    slidesToScroll: true,
    adaptiveHeight: true,
    autoplay: true,
    autoplaySpeed: 3000,
    speed: 800,
    lazyLoad: 'ondemand',
    cssEase: 'linear',
};
