# Uses NodeJS V 9.4.0
image: node:9.4.0

# And to cache them as well.
cache:
  paths:
    - node_modules/
    - .yarn

# Docker images come with yarn preinstalled
before_script:
  - apt-get update -qq && apt-get install

stages:
#   - test
  - push

variables:
  REPOSITORY_HOST: asia.gcr.io
  IMAGE_NAME: $CI_PROJECT_NAME

Build-Push-Docker-Staging:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker info
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_STAG
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_STAG
    NODE_ENV: staging
    REACT_APP_ENV: staging
  environment:
    name: REACT_APP_ENV
    action: staging
  script:
    - yarn run build-stag
    - .gitlab-ci/auth_gcloud.sh
    - .gitlab-ci/push_docker.sh
  only:
    - develop@apps/mola/mola-web

Build-Push-Docker-Production:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_PROD
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_PROD
    NODE_ENV: production
    REACT_APP_ENV: production
  environment:
    name: REACT_APP_ENV
    action: production
  script:
    - yarn run build-prod
    - .gitlab-ci/auth_gcloud.sh
    - .gitlab-ci/push_docker.sh
  only:
    - master@apps/mola/mola-web