variables:
  DOCKER_HOST: 'tcp://localhost:2375'

stages:
  - build
  - push_docker

.push_docker: &push_docker
  image: google/cloud-sdk
  stage: push_docker
  services:
    - docker:18.09-dind
  after_script:
    - ./.gitlab/prepare_files.sh
    - ./.gitlab/auth_gcloud.sh
    - ./.gitlab/push_docker.sh
  except:
    changes:
      - 'qa_release_notes.md'

.build: &build
  image: node:8-alpine
  stage: build
  artifacts:
    paths:
      - node_modules/
      - build/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .node_modules/
  script:
    - apk --no-cache --update add g++ make bash zlib-dev libpng-dev
    - '[ -d .node_modules ] && mv .node_modules/ node_modules/'
    - yarn install --no-progress --production=false
    - node_modules/.bin/babel-node tools/run build -- --release --docker
    - cp -r node_modules/ .node_modules/
    - yarn install --no-progress --production=true

build_staging:
  <<: *build
  only:
    - beta@apps/mola/mola-web
    - develop@apps/mola/mola-web
    - new-design-dev@apps/mola/mola-web
  variables:
    ENV: staging
    NODE_ENV: staging
    REACT_APP_ENV: staging
    GCS_PATH: gs://sstv-staging-cdn/mola
    CDN_PATH: https://cdn.stag.supersoccer.tv/mola

build_production:
  <<: *build
  only:
    - master@apps/mola/mola-web
  variables:
    ENV: production
    NODE_ENV: production
    REACT_APP_ENV: production
    GCS_PATH: gs://koicdn-com/mola01
    CDN_PATH: https://mola01.koicdn.com

push_docker_staging:
  <<: *push_docker
  script:
    - echo "Pushing docker image to staging..."
  variables:
    GCLOUD_SERVICE_KEY: $GCR_SSTV_KEY_STAG
    GCLOUD_PROJECT_ID: $GCR_SSTV_PROJECT_STAG
    GCS_PATH: gs://sstv-staging-cdn/mola
    CDN_PATH: https://cdn.stag.supersoccer.tv/mola
  only:
    - beta@apps/mola/mola-web
    - develop@apps/mola/mola-web
    - new-design-dev@apps/mola/mola-web

push_docker_production:
  <<: *push_docker
  script:
    - echo "Pushing docker image to production..."
  variables:
    GCLOUD_SERVICE_KEY: $GCR_SSTV_KEY_PROD
    GCLOUD_PROJECT_ID: $GCR_SSTV_PROJECT_PROD
    GCS_PATH: gs://koicdn-com/mola01
    CDN_PATH: https://mola01.koicdn.com
  only:
    - master@apps/mola/mola-web
