image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - export DOCKER_HOST="tcp://localhost:2375"
  - docker info
  - apt-get update -qq && apt-get install

stages:
#   - test
  - build
  - push

Build My App:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - npm run build

variables:
  REPOSITORY_HOST: asia.gcr.io
  IMAGE_NAME: $CI_PROJECT_NAME

Build-Push-Docker-Staging:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker info
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_STAG
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_STAG
    NODE_ENV: staging
    REACT_APP_ENV: staging
  script:
    - npm build-stag
    - .gitlab-ci/auth_gcloud.sh
    - .gitlab-ci/push_docker.sh
  only:
    - develop@apps/mola/mola-web

Build-Push-Docker-Production:
  stage: push
  image: google/cloud-sdk
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker info
    - apt-get update -qq && apt-get install -y -qq nodejs
    - npm install
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_PROD
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_PROD
    NODE_ENV: production
    REACT_APP_ENV: production
  script:
    - npm build-prod
    - .gitlab-ci/auth_gcloud.sh
    - .gitlab-ci/push_docker.sh
  only:
    - master@apps/mola/mola-web