stages:
#   - test
#   - build
  - push_docker

.job_template: &push_docker
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker info
    - ./.gitlab-ci/auth_gcloud.sh
    - ./.gitlab-ci/push_docker.sh
    - ./.gitlab-ci/deploy.sh

variables:
  REPOSITORY_HOST: asia.gcr.io
  IMAGE_NAME: $CI_PROJECT_NAME
  APP_NAME: $CI_PROJECT_NAME
  BASE_URL: github.com/supersoccer
  NAMESPACE: frontend
  FOLDER_NAME: applications

push_docker_staging:
  stage: push_docker
  <<: *push_docker
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_STAG
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_STAG
    NODE_ENV: staging
    REACT_APP_ENV: staging
    DEPLOYMENT_REPO: core-staging-cluster-01
  only:
    - develop@apps/mola/mola-web

push_docker_production:
  stage: push_docker
  <<: *push_docker
  variables:
    GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY_PROD
    GCLOUD_PROJECT_ID: $GCLOUD_PROJECT_ID_PROD
    NODE_ENV: production
    REACT_APP_ENV: production
    DEPLOYMENT_REPO: core-prod-cluster-01
  only:
    - master@apps/mola/mola-web
