stages:
  #   - test
  #   - build
  - push_docker

.job_template: &push_docker
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - docker info
    - ./.gitlab/auth_gcloud.sh
    - ./.gitlab/push_docker.sh

push_docker_staging:
  stage: push_docker
  <<: *push_docker
  variables:
    GCLOUD_SERVICE_KEY: $GCR_SSTV_KEY_STAG
    GCLOUD_PROJECT_ID: $GCR_SSTV_PROJECT_STAG
    NODE_ENV: staging
    REACT_APP_ENV: staging
    GCS_PATH: gs://sstv-staging-cdn/mola
    CDN_PATH: https://cdn.stag.supersoccer.tv/mola
  only:
    - beta@apps/mola/mola-web
