FROM node:8-alpine as builder

RUN apk --no-cache update && apk --no-cache add g++ make bash zlib-dev libpng-dev && rm -fr /var/cache/apk/*

WORKDIR /mola-web

COPY . .

USER node

ENTRYPOINT [ "node" ]

CMD [ "./build/server.js" ]
