# Before RUNNING Dockerfile, Please make sure to run `yarn build-{env} --release`
FROM node:8-alpine

WORKDIR /var/www/mola-web

ARG REACT_APP_ENV=staging

COPY .npmrc .
COPY package*.json .

# Install Node.js dependencies
RUN yarn install --no-progress

RUN echo $REACT_APP_ENV

COPY . .
RUN yarn build -- --release --docker REACT_APP_ENV=${REACT_APP_ENV} NODE_ENV=${REACT_APP_ENV}

# Run the container under "node" user by default
USER node

CMD [ "node", "./build/server.js" ]
