const GET_ARTICLES_DETAIL_LOADING = 'GET_ARTICLES_DETAIL_LOADING'
const GET_ARTICLES_DETAIL_SUCCESS = 'GET_ARTICLES_DETAIL_SUCCESS'
const GET_ARTICLES_DETAIL_ERROR = 'GET_ARTICLES_DETAIL_ERROR'

export {
  GET_ARTICLES_DETAIL_LOADING,
  GET_ARTICLES_DETAIL_SUCCESS,
  GET_ARTICLES_DETAIL_ERROR,
}