const GET_PROGRAMME_GUIDES_LOADING =
  'channels/GET_PROGRAMME_GUIDES_LOADING';
const GET_PROGRAMME_GUIDES_SUCCESS =
  'channels/GET_PROGRAMME_GUIDES_SUCCESS';
const GET_PROGRAMME_GUIDES_ERROR =
  'channels/GET_PROGRAMME_GUIDES_ERROR';

const GET_CHANNELS_PLAYLIST_LOADING = 'channels/GET_CHANNELS_PLAYLIST_LOADING';
const GET_CHANNELS_PLAYLIST_SUCCESS = 'channels/GET_CHANNELS_PLAYLIST_SUCCESS';
const GET_CHANNELS_PLAYLIST_ERROR = 'channels/GET_CHANNELS_PLAYLIST_ERROR';
const GET_PROGRAMME_GUIDES = 'channels/GET_PROGRAMME_GUIDES'

export {
  GET_PROGRAMME_GUIDES_LOADING,
  GET_PROGRAMME_GUIDES_SUCCESS,
  GET_PROGRAMME_GUIDES_ERROR,
  GET_CHANNELS_PLAYLIST_LOADING,
  GET_CHANNELS_PLAYLIST_SUCCESS,
  GET_CHANNELS_PLAYLIST_ERROR,
  GET_PROGRAMME_GUIDES,
};
