const GET_FEATURE_PLAYLIST_LOADING = 'feature/GET_FEATURE_PLAYLIST_LOADING'
const GET_FEATURE_PLAYLIST_SUCCESS = 'feature/GET_FEATURE_PLAYLIST_SUCCESS'
const GET_FEATURE_PLAYLIST_ERROR = 'feature/GET_FEATURE_PLAYLIST_ERROR'

const GET_FEATURE_VIDEO = 'feature/GET_FEATURE_VIDEO'

const GET_FEATURE_BANNER_LOADING = 'feature/GET_FEATURE_BANNER_LOADING'
const GET_FEATURE_BANNER_SUCCESS = 'feature/GET_FEATURE_BANNER_SUCCESS'
const GET_FEATURE_BANNER_ERROR = 'feature/GET_FEATURE_BANNER_ERROR'

const GET_FEATURE_ARTICLE_LOADING = 'feature/GET_FEATURE_ARTICLE_LOADING'
const GET_FEATURE_ARTICLE_SUCCESS = 'feature/GET_FEATURE_ARTICLE_SUCCESS'
const GET_FEATURE_ARTICLE_ERROR = 'feature/GET_FEATURE_ARTICLE_ERROR'

export {
  GET_FEATURE_PLAYLIST_LOADING,
  GET_FEATURE_PLAYLIST_SUCCESS,
  GET_FEATURE_PLAYLIST_ERROR,
  GET_FEATURE_VIDEO,
  GET_FEATURE_BANNER_LOADING,
  GET_FEATURE_BANNER_SUCCESS,
  GET_FEATURE_BANNER_ERROR,
  GET_FEATURE_ARTICLE_LOADING,
  GET_FEATURE_ARTICLE_SUCCESS,
  GET_FEATURE_ARTICLE_ERROR,
}
