const GET_FEATURE_PLAYLIST_LOADING = 'feature/GET_FEATURE_PLAYLIST_LOADING'
const GET_FEATURE_PLAYLIST_SUCCESS = 'feature/GET_FEATURE_PLAYLIST_SUCCESS'
const GET_FEATURE_PLAYLIST_ERROR = 'feature/GET_FEATURE_PLAYLIST_ERROR'

const GET_FEATURE_VIDEO = 'feature/GET_FEATURE_VIDEO'

export { GET_FEATURE_PLAYLIST_LOADING, GET_FEATURE_PLAYLIST_SUCCESS, GET_FEATURE_PLAYLIST_ERROR, GET_FEATURE_VIDEO }
