const GET_HOME_PLAYLIST = 'home/GET_HOME_PLAYLIST'
const GET_HOME_VIDEO = 'home/GET_HOME_VIDEO'
const UPDATE_ACTIVE_PLAYLIST = 'home/UPDATE_ACTIVE_PLAYLIST'

export {
    GET_HOME_PLAYLIST,
    GET_HOME_VIDEO,
    UPDATE_ACTIVE_PLAYLIST,
}
