const GET_MATCHES_PLAYLIST_LOADING = 'matches/GET_MATCHES_PLAYLIST_LOADING'
const GET_MATCHES_PLAYLIST_SUCCESS = 'matches/GET_MATCHES_PLAYLIST_SUCCESS'
const GET_MATCHES_PLAYLIST_ERROR = 'matches/GET_MATCHES_PLAYLIST_ERROR'

const GET_MATCHES_VIDEO = 'matches/GET_MATCHES_VIDEO'
const UPDATE_ACTIVE_MATCHES_PLAYLIST = 'matches/UPDATE_ACTIVE_MATCHES_PLAYLIST'

export { GET_MATCHES_PLAYLIST_LOADING, GET_MATCHES_PLAYLIST_SUCCESS, GET_MATCHES_PLAYLIST_ERROR, GET_MATCHES_VIDEO, UPDATE_ACTIVE_MATCHES_PLAYLIST }
