const GET_MOVIE_DETAIL_LOADING = 'movie-detail/GET_MOVIE_DETAIL_LOADING';
const GET_MOVIE_DETAIL_SUCCESS = 'movie-detail/GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_ERROR = 'movie-detail/GET_MOVIE_DETAIL_ERROR';

// const GET_HOME_VIDEO = 'home/GET_HOME_VIDEO';
// const UPDATE_ACTIVE_PLAYLIST = 'home/UPDATE_ACTIVE_PLAYLIST';

export {
  GET_MOVIE_DETAIL_LOADING,
  GET_MOVIE_DETAIL_SUCCESS,
  GET_MOVIE_DETAIL_ERROR
}
