const GET_NOTIFICATIONS_LOADING = 'GET_NOTIFICATIONS_LOADING'
const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR'
const UPDATE_NOTIFICATIONS_LOADING = 'UPDATE_NOTIFICATIONS_LOADING'
const UPDATE_NOTIFICATIONS_SUCCESS = 'UPDATE_NOTIFICATIONS_SUCCESS'
const UPDATE_NOTIFICATIONS_ERROR = 'UPDATE_NOTIFICATIONS_ERROR'
const TOGGLE_POPUP_NOTIFICATIONS = 'TOGGLE_POPUP_NOTIFICATIONS'

const GET_TOTAL_NOTIFICATIONS_LOADING = 'GET_TOTAL_NOTIFICATIONS_LOADING'
const GET_TOTAL_NOTIFICATIONS_SUCCESS = 'GET_TOTAL_NOTIFICATIONS_SUCCESS'
const GET_TOTAL_NOTIFICATIONS_ERROR = 'GET_TOTAL_NOTIFICATIONS_ERROR'

export {
  GET_NOTIFICATIONS_LOADING,
  GET_NOTIFICATIONS_SUCCESS,
  GET_NOTIFICATIONS_ERROR,
  UPDATE_NOTIFICATIONS_LOADING,
  UPDATE_NOTIFICATIONS_SUCCESS,
  UPDATE_NOTIFICATIONS_ERROR,
  TOGGLE_POPUP_NOTIFICATIONS,
  GET_TOTAL_NOTIFICATIONS_LOADING,
  GET_TOTAL_NOTIFICATIONS_SUCCESS,
  GET_TOTAL_NOTIFICATIONS_ERROR,
}
