const GET_PARTNERS_LOADING = 'partners/GET_PARTNERS_LOADING'
const GET_PARTNERS_SUCCESS = 'partners/GET_PARTNERS_SUCCESS'
const GET_PARTNERS_ERROR = 'partners/GET_PARTNERS_ERROR'

export { GET_PARTNERS_LOADING, GET_PARTNERS_SUCCESS, GET_PARTNERS_ERROR }
