const GET_PLAYLIST_LOADING = 'playlist/GET_PLAYLIST_LOADING'
const GET_PLAYLIST_SUCCESS = 'playlist/GET_PLAYLIST_SUCCESS'
const GET_PLAYLIST_ERROR = 'playlist/GET_PLAYLIST_ERROR'
const GET_VIDEO_ERROR = 'playlist/GET_VIDEO_ERROR'
const GET_PLAYLIST_VIDEO = 'feature/GET_PLAYLIST_VIDEO'

export { GET_PLAYLIST_LOADING, GET_PLAYLIST_SUCCESS, GET_PLAYLIST_ERROR, GET_PLAYLIST_VIDEO, GET_VIDEO_ERROR }
