const GET_RECOMMENDATION_LOADING = 'recommendation/GET_RECOMMENDATION_LOADING'
const GET_RECOMMENDATION_SUCCESS = 'recommendation/GET_RECOMMENDATION_SUCCESS'
const GET_RECOMMENDATION_ERROR = 'recommendation/GET_RECOMMENDATION_ERROR'

export { GET_RECOMMENDATION_LOADING, GET_RECOMMENDATION_SUCCESS, GET_RECOMMENDATION_ERROR }
