const GET_SEARCH_LOADING = 'search/GET_SEARCH_LOADING';
const GET_SEARCH_SUCCESS = 'search/GET_SEARCH_SUCCESS';
const GET_SEARCH_ERROR = 'search/GET_SEARCH_ERROR';

const GET_SEARCH_GENRE_LOADING = 'search/GET_SEARCH_GENRE_LOADING';
const GET_SEARCH_GENRE_SUCCESS = 'search/GET_SEARCH_GENRE_SUCCESS';
const GET_SEARCH_GENRE_ERROR = 'search/GET_SEARCH_GENRE_ERROR';

export {
  GET_SEARCH_GENRE_LOADING,
  GET_SEARCH_GENRE_SUCCESS,
  GET_SEARCH_GENRE_ERROR,
  GET_SEARCH_LOADING,
  GET_SEARCH_SUCCESS,
  GET_SEARCH_ERROR,
}
