const GET_VIDEOS_LOADING = 'search/GET_VIDEOS_LOADING';
const GET_VIDEOS_SUCCESS = 'search/GET_VIDEOS_SUCCESS';
const GET_VIDEOS_ERROR = 'search/GET_VIDEOS_ERROR';

export {
  GET_VIDEOS_LOADING,
  GET_VIDEOS_SUCCESS,
  GET_VIDEOS_ERROR,
}
