const GET_VIDEOS_LOADING = 'search/GET_VIDEOS_LOADING';
const GET_VIDEOS_SUCCESS = 'search/GET_VIDEOS_SUCCESS';
const GET_VIDEOS_ERROR = 'search/GET_VIDEOS_ERROR';

const GET_SEARCH_LOADING = 'search/GET_SEARCH_LOADING';
const GET_SEARCH_SUCCESS = 'search/GET_SEARCH_SUCCESS';
const GET_SEARCH_ERROR = 'search/GET_SEARCH_ERROR';

export {
  GET_VIDEOS_LOADING,
  GET_VIDEOS_SUCCESS,
  GET_VIDEOS_ERROR,

  GET_SEARCH_LOADING,
  GET_SEARCH_SUCCESS,
  GET_SEARCH_ERROR,
}
