const GET_SPORT_PLAYLIST_LOADING = 'sport/GET_SPORT_PLAYLIST_LOADING'
const GET_SPORT_PLAYLIST_SUCCESS = 'sport/GET_SPORT_PLAYLIST_SUCCESS'
const GET_SPORT_PLAYLIST_ERROR = 'sport/GET_SPORT_PLAYLIST_ERROR'

const GET_SPORT_VIDEO = 'sport/GET_SPORT_VIDEO'
const UPDATE_ACTIVE_SPORT_PLAYLIST = 'sport/UPDATE_ACTIVE_SPORT_PLAYLIST'

export { GET_SPORT_PLAYLIST_LOADING, GET_SPORT_PLAYLIST_SUCCESS, GET_SPORT_PLAYLIST_ERROR, GET_SPORT_VIDEO, UPDATE_ACTIVE_SPORT_PLAYLIST }
