const GET_ALL_SUBSCRIPTION_LOADING = 'not-found/GET_ALL_SUBSCRIPTION_LOADING'
const GET_ALL_SUBSCRIPTION_SUCCESS = 'not-found/GET_ALL_SUBSCRIPTION_SUCCESS'
const GET_ALL_SUBSCRIPTION_ERROR = 'not-found/GET_ALL_SUBSCRIPTION_ERROR'

export { GET_ALL_SUBSCRIPTION_LOADING, GET_ALL_SUBSCRIPTION_SUCCESS, GET_ALL_SUBSCRIPTION_ERROR }
