const GET_ALL_SUBSCRIPTION_LOADING = 'subscribe/GET_ALL_SUBSCRIPTION_LOADING'
const GET_ALL_SUBSCRIPTION_SUCCESS = 'subscribe/GET_ALL_SUBSCRIPTION_SUCCESS'
const GET_ALL_SUBSCRIPTION_ERROR = 'subscribe/GET_ALL_SUBSCRIPTION_ERROR'

const GET_USER_SUBSCRIPTION_LOADING = 'subscribe/GET_USER_SUBSCRIPTION_LOADING'
const GET_USER_SUBSCRIPTION_SUCCESS = 'subscribe/GET_USER_SUBSCRIPTION_SUCCESS'
const GET_USER_SUBSCRIPTION_ERROR = 'subscribe/GET_USER_SUBSCRIPTION_ERROR'

export {
  GET_ALL_SUBSCRIPTION_LOADING,
  GET_ALL_SUBSCRIPTION_SUCCESS,
  GET_ALL_SUBSCRIPTION_ERROR,
  GET_USER_SUBSCRIPTION_LOADING,
  GET_USER_SUBSCRIPTION_SUCCESS,
  GET_USER_SUBSCRIPTION_ERROR,
}
