const UPDATE_USER_AUTH_LOADING = '~/UPDATE_USER_AUTH_LOADING';
const UPDATE_USER_AUTH_SUCCESS = '~/UPDATE_USER_AUTH_SUCCESS';
const UPDATE_USER_AUTH_ERROR = '~/UPDATE_USER_AUTH_ERROR';

const GET_USER_INFO_LOADING = '~/GET_USER_INFO_LOADING';
const GET_USER_INFO_SUCCESS = '~/GET_USER_INFO_SUCCESS';
const GET_USER_INFO_ERROR = '~/GET_USER_INFO_ERROR';

export {
  UPDATE_USER_AUTH_LOADING,
  UPDATE_USER_AUTH_SUCCESS,
  UPDATE_USER_AUTH_ERROR,
  GET_USER_INFO_LOADING,
  GET_USER_INFO_SUCCESS,
  GET_USER_INFO_ERROR,
}
